/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.gradle.api.plugins.JavaPluginConvention;
import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'org.example.greeting' plugin.
 */
public class GreetingPluginTest {
    @Test public void pluginRegistersATask() {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("java");
        project.getPlugins().apply("org.example.greeting");

        // Verify the result
        assertNotNull(project.getConvention().getPlugin(JavaPluginConvention.class).getSourceSets().findByName("functionalTest"));
    }
}
